- id: lychee
  name: lychee
  description: "Run 'lychee' for fast, async, stream-based link checking"
  entry: lycheeverse/lychee:0.14
  language: docker_image
  args: []
  types: [text]
  pass_filenames: true
  require_serial: true
  additional_dependencies: []
